from django.urls import path
from .views import (
    register,
    login_view,
    attendance_view,
    user_list_view,
    user_detail_view,
    department_list_view,
    department_detail_view,
    section_list_view,
    section_detail_view,
    subject_list_view,
    subject_detail_view,
    bulk_student_upload_view,
    bulk_faculty_upload_view,
    bulk_subject_upload_view,
    export_attendance_excel_view,
    export_attendance_date_wise_excel_view,
    attendance_portal_freeze_view,
    bulk_attendance_upload_view,
    sample_student_registration_excel_view,
    sample_faculty_registration_excel_view,
    sample_subjects_excel_view,
    sample_bulk_attendance_excel_view,
)

urlpatterns = [
    path('register/', register),
    path('login/', login_view),
    path('attendance/', attendance_view),
    path('attendance-portal-freeze/', attendance_portal_freeze_view),
    path('users/', user_list_view),
    path('users/<int:pk>/', user_detail_view),
    path('departments/', department_list_view),
    path('departments/<int:pk>/', department_detail_view),
    path('sections/', section_list_view),
    path('sections/<int:pk>/', section_detail_view),
    path('subjects/', subject_list_view),
    path('subjects/<int:pk>/', subject_detail_view),
    path('students/bulk-upload/', bulk_student_upload_view),
    path('faculty/bulk-upload/', bulk_faculty_upload_view),
    path('subjects/bulk-upload/', bulk_subject_upload_view),
    path('export/attendance-data/', export_attendance_excel_view),
    path('export/attendance-date-wise/', export_attendance_date_wise_excel_view),
    path('attendance/bulk-upload/', bulk_attendance_upload_view),
    path('samples/student-registration/', sample_student_registration_excel_view),
    path('samples/faculty-registration/', sample_faculty_registration_excel_view),
    path('samples/subjects/', sample_subjects_excel_view),
    path('samples/bulk-attendance/', sample_bulk_attendance_excel_view),
]
