# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subject_add_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hours',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Number of hours the student attended (out of total hours for this session/date).',
                max_digits=6,
                null=True,
            ),
        ),
    ]
