# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_attendance_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Total hours for this session/date.',
                max_digits=6,
                null=True,
            ),
        ),
    ]
