# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_attendance_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visible_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
