# Generated by Django 6.0.3 on 2026-03-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of hours the student attended (attended_hours).', max_digits=6, null=True),
        ),
    ]
