# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_attendance_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_subject_ids',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
