# Generated by Django 6.0.3 on 2026-08-04 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_attendanceportalcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDepartmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='core.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_department_sections', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='core.section')),
            ],
            options={
                'verbose_name': 'Faculty Department Section',
                'verbose_name_plural': 'Faculty Department Sections',
                'unique_together': {('faculty', 'department', 'section')},
            },
        ),
    ]
