# Generated by Django 6.0.3 on 2026-08-07 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_facultydepartmentsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('sections', models.CharField(help_text='Comma-separated section names', max_length=500)),
                ('duration_minutes', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('current_qr_token', models.CharField(max_length=100, unique=True)),
                ('token_expires_at', models.DateTimeField()),
                ('token_refresh_interval', models.IntegerField(default=5, help_text='Token refresh interval in seconds')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Attendance Session',
                'verbose_name_plural': 'QR Attendance Sessions',
            },
        ),
        migrations.CreateModel(
            name='QRAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique identifier for the device used', max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.qrattendancesession')),
            ],
            options={
                'verbose_name': 'QR Attendance Record',
                'verbose_name_plural': 'QR Attendance Records',
                'unique_together': {('session', 'device_id'), ('session', 'student')},
            },
        ),
    ]
