# Generated by Django 6.0.3 on 2026-08-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_qrattendancesession_qrattendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrattendancesession',
            name='branches',
            field=models.CharField(blank=True, default='', help_text='Comma-separated branch codes', max_length=500),
        ),
        migrations.AlterField(
            model_name='qrattendancesession',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
