# Generated by Django 6.0.3 on 2026-08-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_qrattendancesession_qrattendancerecord'),
    ]

    operations = [
        # This field already exists in the database, marking as no-op
        migrations.RunSQL(
            sql="SELECT 1",  # No-op SQL
            reverse_sql="SELECT 1",  # No-op SQL
        ),
    ]
