# Generated by Django 6.0.3 on 2026-08-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_qrattendancesession_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrattendancesession',
            name='custom_session_id',
            field=models.CharField(blank=True, help_text='Random 5-digit session ID for display', max_length=10, null=True, unique=True),
        ),
    ]
