# Generated by Django 6.0.3 on 2026-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_qrattendancesession_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrattendancesession',
            name='custom_session_id',
            field=models.CharField(blank=True, help_text='Custom session ID for manual entry', max_length=50, null=True, unique=True),
        ),
    ]
